# Generated by Django 3.2.8 on 2021-10-14 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash_value', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('auto', models.BooleanField(default=True)),
                ('image_pos', models.ImageField(upload_to='event/pos/')),
                ('image_neg', models.ImageField(upload_to='event/neg/')),
            ],
        ),
    ]
