# Generated by Django 3.2.8 on 2021-10-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='hash_value',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='image_neg',
            field=models.ImageField(blank=True, null=True, upload_to='event/neg/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='image_pos',
            field=models.ImageField(blank=True, null=True, upload_to='event/pos/'),
        ),
    ]
