# Generated by Django 3.2.8 on 2021-10-14 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('camera_name', models.CharField(max_length=16)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('is_authorised', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='event/images/')),
                ('is_video_recorded', models.BooleanField(default=False)),
                ('video', models.FileField(null=True, upload_to='event/videos/')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part.part')),
            ],
        ),
    ]
