# Generated by Django 3.2.8 on 2021-10-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20211014_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='camera_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='event/videos/'),
        ),
    ]
